export const ADD_MESSAGE = 'message/ADD_MESSAGE';
export const REMOVE_MESSAGE = 'message/REMOVE_MESSAGE';
export const SET_MESSAGE_DIRECTION = 'message/SET_MESSAGE_DIRECTION';
export const UPDATE_MESSAGE_CONTACT_NAME = 'message/UPDATE_MESSAGE_CONTACT_NAME';
export const SET_GLOBAL_MESSAGE_DIRECTION = 'message/SET_GLOBAL_MESSAGE_DIRECTION';
